---
title: "Client Report - Introduction"
subtitle: "Course DS 250"
author: "Max Smith"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
#| label: libraries
#| include: false
import pandas as pd
import numpy as np
import plotly.express as px

# the following for mac users ro download data through the Internet
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
```


## Elevator pitch

In this analysis, we will take a look at a data set based on cars. In this data we have information like manufacturer, miles per gallon, engine size, and a couple others. We will be answering the question of whether a cars fuel efficiency gets better or worse as the engine size increases. In this report we will also see the top 5 rows in our data set.

```{python}
#| label: project data
#| code-summary: Read and format project data

df = pd.read_csv('mpg.csv')

```

__Highlight the Questions and Tasks__

## QUESTION|TASK 1

Finish the readings and be prepared with any questions to get your environment working smoothly. 

Finished all readings.


## QUESTION|TASK 2

In VS Code, write a python script to create the example chart from section 3.2.2 of the textbook 

The graph provided shows the negative relationship between engine sizes and the vehicles mile per gallon. This tells us that as a cars engine gets bigger, the cars mpg decreases. There is a small group of semi-outliers with bigger engines that have slightly better than average mpg, however it is still only comparable to the cars with the smallest engines that have the worst mpg.

_include figures in chunks and discuss your findings in the figure._

```{python}
#| label: Q2 chart
#| code-summary: plot example
#| fig-cap: "My useless chart"
#| fig-align: center
# Include and execute your code here

chart = px.scatter(df,
    x="displ", 
    y="hwy"
)
chart.show()
```


## QUESTION|TASK 3

Your final report should also include the markdown table created from the following

From this table, we can see that the top 5 cars in the table are audi a4s varying in year and hwy. This tells us that the table is most likely alphabetically sorted by manufacturer.

```{python}
#| label: Q3 table
#| code-summary: table example
#| tbl-cap: "Not much of a table"
#| tbl-cap-location: top
# Include and execute your code here
print(df
  .head(5)
  .filter(["manufacturer", "model","year", "hwy"])
  .to_markdown(index=False))

```
